rvm:
- 2.3.0
- 2.4.2
- jruby-9.0
sudo: false
cache: bundler
matrix:
  allow_failures:
    - rvm: jruby-9.0
branches:
  - master
  - rubocop-integration
jobs:
  include:
    - stage: Linters
      script: bundle exec rubocop
    - stage: Tests
      script: bundle exec rspec
